/**
 * Parcours – Activité du 13/06
 *
 * Chaque entrée représente une étape du questionnaire, qu'il s'agisse
 * d'un signe distinctif, d'un défi, d'une énigme ou d'un bonus manuel.
 */
const QUESTIONS = [
  {
    id: 3,
    stage: "Étape 2  – 50.191682, 4.383208 ",
    section: "Signe distinctif – 50.191682, 4.383208",
    type: "free",
    question:
      "Quel mot imaginaire est formé par les première lettres des panneaux directionnels que vous voyez?",
    instructions: "Inscrivez les lettres dans l’ordre de lecture : de haut en bas puis de gauche à droite.",
    answer: "CVCDBC",
    points: 0,
    nextBlock: {
      title: "Lieu validé",
      value: "Signe distinctif trouvé",
      label: "Vous pouvez maintenant répondre à l’énigme de l’étape.",
    },
  },
  {
    id: 4,
    stage: "Étape 2 – 50.191682, 4.383208",
    section: "Énigme",
    type: "free",
    question: "E0 . AIB GBF D . CID HEF",
    timer: 10,
    answerPattern: "^\\D*50\\D*192726\\D*4\\D*394856\\D*$",
    answers: [
      "50.192726, 4.394856",
      "50.192726 4.394856",
      "501927264394856",
      "50 192726 4 394856",
    ],
    points: 250,
    hint: {
      text: "Ce ne sont ni des mots ni des lettres.",
      penalty: -50,
      label: "Voir l’indice (-50 points)",
    },
    instructions: "Décoder le code ci-dessus",
    answerDisplay: "La bonne piste vous menait aux coordonnées suivantes.",
    nextBlock: {
      title: "Prochaine coordonnée",
      value: "50.192726, 4.394856",
      label: "Énigme résolue, direction la prochaine étape !",
    },
  },
  {
    id: 5,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Signe distinctif – 50.192726, 4.394856",
    type: "free",
    question:
      "Dans le silence paisible des sentiers apprivoisés, là où ni moteurs pressés ni tumulte ne viennent troubler la lente respiration du paysage, vous avancez sur un ruban discret qui enlace la nature et guide les voyageurs patients. Dites-moi, sous vos pas et au fil de cette voie dédiée aux marcheurs et aux cyclistes rêveurs, quel est le nombre secret qui baptise ce chemin où le temps semble suspendu ?",
    answerPattern: "^.*\\b109\\b.*$", points: 0,
    nextBlock: {
      title: "Lieu validé",
      value: "Coordonnée validée",
      label: "Regroupez-vous cette étape sera chronométrée. Prêt ? Partez ! ",
    },
  },
  {
    id: 6,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Vrai/Faux",
    type: "mcq",
    question: "Le lac est alimenté uniquement par la pluie",
    options: ["Vrai", "Faux"],
    answer: "Faux",
    answerBubble:
      "En réalité, même si la pluie contribue au niveau de l’eau, ce n’est qu’une petite partie.\nLe lac est principalement alimenté par :\n• la rivière de l’Eau d’Heure\n• d’autres apports hydrauliques contrôlés.",
    points: 150,
    timer: 7,
  },
  {
    id: 7,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Vrai/Faux",
    type: "mcq",
    question: "Un ancien village entier repose aujourd’hui sous les eaux du lac.",
    options: ["Vrai", "Faux"],
    answer: "Faux",
    answerBubble:
      "C’est une idée qui revient souvent, mais ici :\n• aucun village complet n’a été englouti\n• il y avait surtout des terres agricoles, des bois et quelques bâtiments isolés.\n\nContrairement à d’autres barrages en Europe, il n’y a pas de « ville fantôme » sous l’eau ici, même si le mythe est tentant.\n\nExemples célèbres ailleurs en Europe :\n• 🇮🇹 Lac de Resia : un village submergé dans les années 1950, seul le clocher de l’église dépasse encore.\n • 🇪🇸 Embalse de Sau : un ancien village repose sous le lac, et quand le niveau baisse, les ruines réapparaissent.\n • 🇫🇷 Lac de Serre-Ponçon : plusieurs villages déplacés ou détruits, avec la chapelle Saint-Michel conservée au milieu des eaux.\n • 🇬🇧 Ladybower Reservoir : le village de Derwent a été englouti, et lors des sécheresses, des vestiges réapparaissent.", points: 150,
    timer: 10,
  },
  {
    id: 8,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Vrai/Faux",
    type: "mcq",
    question: "L’eau du lac peut être déplacée entre différents bassins",
    options: ["Vrai", "Faux"],
    answer: "Vrai",
    answerBubble:
      "Plusieurs lacs sont interconnectés : l’eau peut circuler entre eux selon les besoins grâce à des installations techniques.\nLe barrage de la Plate Taille joue un rôle central dans ce système.\n\nCela permet de gérer :\n• les niveaux d’eau\n• la production d’énergie\n• la sécurité hydraulique.",
    points: 150,
    timer: 15,
  },
  {
    id: 9,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Vrai/Faux",
    type: "mcq",
    question: "Le lac a été créé naturellement au fil du temps",
    options: ["Vrai", "Faux"],
    answer: "Faux",
    answerBubble: "Il s’agit d’un lac artificiel, créé par des barrages dans les années 1970.",
    points: 150,
    timer: 20,
  },
  {
    id: 10,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Vrai/Faux",
    type: "mcq",
    question: "Le niveau de l’eau peut varier selon les besoins énergétiques et la gestion du site",
    options: ["Vrai", "Faux"],
    answer: "Vrai",
    answerBubble:
      "Oui : le niveau peut monter ou descendre en fonction de la gestion du réseau.\nLe site est lié à une centrale de pompage-turbinage (production d’électricité).\n\nEn résumé :\n• on stocke de l’eau quand il y a trop d’énergie\n• on la relâche pour produire de l’électricité quand il y a de la demande.",
    points: 150,
    timer: 20,
    nextBlock: {
      summaryTemplate: "Avec cette épreuve vous avez remporté {points} points.",
      label: "Épreuve terminée, passons à la suite !",
    },
  },
  {
    id: 11,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Signe distinctif – 50.201160, 4.387284",
    type: "free",
    question: "Quels points noeuds indique le panneau le plus proche?",
    instructions: "Réponse à relever sur place pour prouver que vous êtes bien au bon endroit.",
    acceptAny: true,
    answerDisplay: "Réponse relevée sur place.",
    points: 0,
    nextBlock: {
      title: "Lieu validé",
      value: "Coordonnée validée",
      label: "L'étape suivante est chronométrée et assez particulière...<br>Trouvez tout sauf la bonne réponse<br>Prenez votre temps... mais pas trop 😉<br>Vous démarrerez à 500, vous perdrez 1 point par seconde et 15 par 'mauvaise réponse'"
    },
  },
  {
    id: 12,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quelle guerre a-t-il vécue ?",
    options: ["La guerre de Chypre", "La guerre de Cent Ans", "La guerre Froide"],
    answer: "La guerre de Chypre",
    points: 0,
  },
  {
    id: 13,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    type: "mcq",
    question: "Qu’a-t-il reçu à ses 40 ans ?",
    options: [
      "Un vélo et une bouteille d’Ultra",
      "Un vélo et une gourde Ultra",
      "Un VTT et une bouteille d’Ultra",
    ],
    answers: ["Un vélo et une bouteille d’Ultra", "Un VTT et une bouteille d’Ultra"],
    points: 0,
  },
  {
    id: 14,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Dans quelle rue a-t-il grandi ?",
    options: ["Rue de la planche-au-pêcheur", "Rue planche au pêcheur", "Rue planche aux pêcheurs"],
    answer: "Rue de la planche-au-pêcheur",
    points: 0,
  },
  {
    id: 15,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quel est son chatbot IA favori ?",
    options: ["Copilot", "ChatGPT", "Claude"],
    answer: "Copilot",
    points: 0,
  },
  {
    id: 16,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Où a t il passé ses dernières vacances ?",
    options: ["Albanie", "Parme", "Croatie"],
    answer: "Albanie",
    points: 0,
  },
  {
    id: 17,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quel sport pratique-t-il en salle ?",
    options: ["Badminton", "Paddle", "Squash"],
    answers: ["Badminton", "Paddle"],
    points: 0,
  },
  {
    id: 18,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quel est son totem ?",
    options: ["Eyra", "Jaguarondi", "Chat-loutre", "Jaguar"],
    answers: ["Eyra", "Jaguarondi", "Chat-loutre"],
    points: 0,
  },
  {
    id: 19,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    type: "mcq",
    question: "Quelle était sa première voiture ?",
    options: ["Golf", "Volkswagen", "Volksvagen"],
    answers: ["Golf", "Volkswagen"],
    points: 0,
  },
  {
    id: 20,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quelles langues parle t il ?",
    options: ["Français", "Anglais", "Espagnol", "Wallon"],
    answers: ["Français", "Anglais", "Espagnol"],
    points: 0,
  },
  {
    id: 21,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quel est le pays le plus lointain où il s’est rendu en voiture ?",
    options: ["Malte", "Turquie", "Afghanistan"],
    answer: "Afghanistan",
    points: 0,
  },
  {
    id: 22,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    type: "mcq",
    question: "Quel était le nom de son école primaire ?",
    options: ["Saint-Jacques", "Saint-Jacque", "Sainte-Jacques"],
    answer: "Saint-Jacques",
    points: 0,
  },
  {
    id: 23,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quel est l'endroit le plus lointain où il ait voyagé ?",
    options: ["Saint-Louis, USA", "Tokyo", "La Réunion"],
    answer: "La Réunion",
    answerDisplay: "La Réunion",
    points: 0,
  },
  {
    id: 24,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    type: "mcq",
    question: "Dans quelle ville habitait sa grand mère paternelle ?",
    options: ["Courcelles", "Pont-à-Celles", "Courcelle"],
    answer: "Courcelles",
    answerDisplay: "Courcelles",
    points: 0,
  },
  {
    id: 25,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    type: "mcq",
    question: "Comment s’appelaient les chèvres ?",
    options: ["Côtelette et Gigot", "Côtelette et Gigaud", "Côtelettes et Gigot"],
    answer: "Côtelette et Gigot",
    answerDisplay: "Côtelette et Gigot",
    points: 0,
  },
  {
    id: 26,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "À quel étage se trouvait sa chambre d’enfance ?",
    options: ["2ème", "2e", "1er"],
    answers: ["2ème", "2e"],
    points: 0,
  },
  {
    id: 27,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "En quelle année a t il déménagé dans sa maison actuelle ?",
    options: ["2002", "2005", "2010"],
    answer: "2002",
    points: 0,
    henryFinal: true,
    nextBlock: {
      label: "J'espère qu'Henry est fier de vous, Place à la suite !",
    },
  },
  {
    id: 28,
    stage: "Étape 5 – 50.202982, 4.376316",
    section: "Signe distinctif – 50.202982, 4.376316",
    type: "free",
    question:
      "Enracinés précisément au point qui vous a été confié, sans céder à la tentation de vous en éloigner, laissez votre regard explorer les signes qui s’offrent à vous sans faire un pas de plus : quels sont donc les noms des villages qui se révèlent, inscrits sur les panneaux visibles depuis ce lieu exact ?",
    answerPattern: "^(?=.*\\berpion\\b)(?=.*\\bvirelles\\b).*$",
    points: 0,
    nextBlock: {
      title: "Lieu validé",
      value: "Signe distinctif trouvé",
      label: "Vous pouvez maintenant répondre à l’énigme de l’étape.",
    },
  },
  {
    id: 29,
    stage: "Étape 5 – 50.202982, 4.376316",
    section: "Énigme",
    type: "free",
    question: "Décodez : JAJPJ/GDMDWWP",
    instructions: "Tiens encore un code ?",
    answerPattern: "^\\D*50\\D*205750\\D*4\\D*363997\\D*$",
    points: 250,
    hint: {
      text: "Un 3310 vous aurait été bien utile.",
      penalty: -50,
      label: "Voir l’indice (-50 points)",
    },
    answerDisplay: "La bonne piste vous menait aux coordonnées suivantes.",
    nextBlock: {
      title: "Prochaine coordonnée",
      value: "50.205750, 4.363997",
      label: "Toujours en vie ? Alors on continue la balade !",
    },
  },
  {
    id: 30,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Signe distinctif – 50.205750, 4.363997",
    type: "free",
    question:
      "Contemplez l’aval de la vallée sèche d’Erpion, livre ancien aux pages de silence craquelé… Vers quel azimut de la rose des vents s’incline votre être ? Quelle boussole borgne, secrètement fiévreuse, oriente vos pas dans cet immobile suspendu ?",
    answerPattern: "^(?:s\\.?\\s*-?\\s*o\\.?|sud\\s*-?\\s*ouest)$",
    answerDisplay: "Sud Ouest",
    points: 0,
    nextBlock: {
      title: "Lieu validé",
      value: "Coordonnée validée",
      label: "Regroupez-vous cette étape sera chronométrée. Prêt ? Partez ! ",
    },
  },
  {
    id: 31,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question:
      "Dans quelle région naturelle vallonnée, connue pour ses forêts et ses plateaux, se situent les lacs ?",
    options: [
      "la Fagne et la Famenne",
      "la Lorraine belge et la Gaume",
      "le Condroz et le Pays de Herve",
      "l’Ardenne et la Hesbaye",
    ],
    answer: "la Fagne et la Famenne",
    points: 250,
    timer: 20,
  },
  {
    id: 32,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question: "Quelle est l’altitude approximative de la région des lacs?",
    options: [
      "entre 200 et 300 mètres au-dessus du niveau de la mer",
      "entre 20 et 30 mètres au-dessus du niveau de la mer",
      "entre 600 et 700 mètres au-dessus du niveau de la mer",
      "entre 1 200 et 1 300 mètres au-dessus du niveau de la mer",
    ],
    answer: "entre 200 et 300 mètres au-dessus du niveau de la mer",
    points: 250,
    timer: 20,
  },
  {
    id: 33,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "free",
    question: "Les eaux des lacs finissent par rejoindre quel grand fleuve européen ?",
    answers: ["la Meuse", "Meuse"],
    answerDisplay: "la Meuse",
    points: 250,
  },
  {
    id: 34,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "match",
    kind: "match-pairs",
    question: "Reliez les communes et leur démographies",
    instructions: "Reliez chaque commune à la bonne démographie.",
    pairs: [
      { left: "Cerfontaine", right: "~4 500" },
      { left: "Froidchapelle", right: "~3 900" },
      { left: "Walcourt", right: "~18 000" },
      { left: "Philippeville", right: "~9 000" },
      { left: "Florennes", right: "~11 000" },
      { left: "Beaumont", right: "~7 000" },
      { left: "Sivry-Rance", right: "~4 800" },
    ],
    pointsPerMatch: 30,
    easterEgg: {
      icon: "🕵️",
      teaseText: "On dit merci quiii?...",
      finalText: "Merci google!",
      delayMs: 0,
    },
  },
  {
    id: 35,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question: "Peut-on bronzer sur une plage… en regardant des sapins au lieu de palmiers ?",
    options: [
      "oui, sur des plages aménagées au milieu des forêts",
      "non, les plages sont interdites autour des lacs",
      "oui, mais uniquement sur des pontons flottants privés",
      "non, il n’y a que des rochers et aucune plage",
    ],
    answer: "oui, sur des plages aménagées au milieu des forêts",
    points: 250,
  },
  {
    id: 36,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "free",
    question: "Les lacs se trouvent à cheval sur deux provinces. Lesquelles ?",
    answerPattern: "^(?=.*\\bnamur\\b)(?=.*\\bhainaut\\b).*$",
    answerDisplay: "Province de Namur et Province de Hainaut",
    points: 250,
    timer: 20,
  },
  {
    id: 37,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question:
      "Quelle espèce dont on en fait l’élevage, dépasse la population de la ville de Cerfontaine sur le même territoire ?",
    options: ["Les poissons", "Les moutons", "Les chèvres", "Les fourmis"],
    answer: "Les poissons",
    points: 250,
    timer: 20,
  },
  {
    id: 38,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question:
      "Quel secteur économique historique de la région a le + bénéficié de la gestion de l’eau du barrage de l’eau d’heure ?",
    options: [
      "l’industrie",
      "l’horlogerie artisanale",
      "la culture de la vigne",
      "la construction navale",
    ],
    answer: "l’industrie",
    answerDisplay: "Surtout la sidérurgie, notamment dans le bassin de Charleroi",

    points: 250,
    timer: 20,
  },
  {
    id: 39,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "free",
    question: "Quel grand parc naturel couvre une partie de cette région autour des lacs ?",
    answerPattern: "^(?=.*\\bviroin\\b)(?=.*\\bhermeton\\b).*$",
    answerDisplay: "le Parc naturel Viroin-Hermeton",
    points: 250,
  },
  {
    id: 40,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "slider",
    kind: "range-slider",
    question: "Quelle est la superficie totale approximative des lacs ?",
    instructions: "Utilisez la barre de grandeur de 0 à 1500 hectares.",
    slider: { min: 0, max: 1500, step: 1, unit: "ha" },
    target: 600,
    tolerance: 60,
    points: 250,
    answerDisplay: "environ 600 hectares (soit 6 km²)",

  },
  {
    id: 41,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question: "Peut-on dormir sur l’eau… sans bateau ni natation et sans s’appeler Jésus ?",
    options: [
      "oui, avec des hébergements flottants ou au bord direct des lacs",
      "non, dormir sur l’eau y est interdit",
      "oui, mais seulement dans un voilier",
      "non, il n’existe que des campings à plus de 10 km",
    ],
    answer: "oui, avec des hébergements flottants ou au bord direct des lacs",
    points: 250,
    nextBlock: {
      title: "Prochaine coordonnée",
      value: "50.188382, 4.346416",
      label: "Étape suivante (non chronométrée).",
    },
  },
  {
    id: 42,
    stage: "Étape 7 – 50.188382, 4.346416",
    section: "Accès à un objectif annexe",
    kind: "numeric-bonus",
    type: "free",
    question: "Combien de mètres de berges voyez-vous ?",
    instructions: "Prenez votre temps et vos jumelles",
    answerPattern: "^-?\\d+$",
    answerDisplay: "Bonus berges enregistré.",
    points: 0,
    unitPoints: 0.01,
    minValue: 0,
    maxValue: 18500,
    rejectOutOfRange: true,
    absurdWrongMessage:
      "Visiblement les cocktails sont plus forts que prévus 😄",
    outOfRangeMessage: "Visiblement les cocktails sont plus forts que prévus 😄",
    nextBlock: {
      title: "Objectif annexe débloqué",
      value: "J'espère que vous n'avez pas réellement tenté de mesurer...",
      label: "Finissons en harmonie avec la nature",
    },
  },
  {
    id: 43,
    stage: "Étape 7 – 50.188382, 4.346416",
    section: "Épreuve feuilles",
    kind: "acknowledgement",
    question: "Rapportez un maximum de feuilles d’arbres différentes",
    instructions:
      "Règles : Rapportez des espèces de feuilles différentes, Chaque espèce vaut 50 points et sera comptabilisée à l'arrivée",
    answerDisplay: "Épreuve feuilles enregistrée.",
    points: 0,
    nextBlock: {
      title: "Prochaine coordonnée",
      value: "50.186963, 4.374291",
      label: "Étape finale : J'espère que vous êtes prêts",
    },
  },
  {
    id: 44,
    stage: "Étape 8 – 50.186963, 4.374291",
    section: "Objet caché",
    kind: "acknowledgement",
    directResult: true,
    question: "Retrouvez la carte de visite du créateur de ce quizz, elle est cachée quelque part autour de vous.<br>J'ai bien le droit à quelques crédits quand même, non ?😄 ",
    answerDisplay: "Objet caché à vérifier à l’arrivée.",
  },
];
