/**
 * Parcours – Activité du 13/06
 *
 * Chaque entrée représente une étape du questionnaire, qu'il s'agisse
 * d'un signe distinctif, d'un défi, d'une énigme ou d'un bonus manuel.
 */
const QUESTIONS = [
  {
    id: 3,
    stage: "Étape 2 – 50.191682, 4.383208",
    section: "Signe distinctif",
    type: "free",
    question:
      "Quel mot imaginaire est formé par les première lettres des panneaux directionnels que vous voyez?",
    instructions: "Inscrivez les lettres dans l’ordre de lecture : de haut en bas puis de gauche à droite.",
    answer: "CVCDBC",
    points: 0,
    nextBlock: {
      title: "Lieu validé",
      value: "Signe distinctif trouvé",
      label: "Vous pouvez maintenant répondre à l’énigme de l’étape 2.",
    },
  },
  {
    id: 4,
    stage: "Étape 2 – 50.191682, 4.383208",
    section: "Énigme",
    type: "free",
    question: "E0 . AIB GBF D . CID HEF",
    instructions: "Possibilité d’indice (fait perdre 50 points).",
    answerPattern: "^\\D*50\\D*192726\\D*4\\D*394856\\D*$",
    answers: [
      "50.192726, 4.394856",
      "50.192726 4.394856",
      "501927264394856",
      "50 192726 4 394856",
    ],
    points: 250,
    hint: {
      text: "Ce ne sont ni des mots ni des lettres.",
      penalty: -50,
      label: "Voir l’indice (-50 points)",
    },
    answerDisplay: "La bonne piste vous menait aux coordonnées suivantes.",
    nextBlock: {
      title: "Prochaine coordonnée",
      value: "50.192726, 4.394856",
      label: "Étape 3 – Validez le lieu avant d’attaquer le Vrai/Faux.",
    },
  },
  {
    id: 5,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Signe distinctif",
    type: "free",
    question:
      "Dans le silence paisible des sentiers apprivoisés, là où ni moteurs pressés ni tumulte ne viennent troubler la lente respiration du paysage, vous avancez sur un ruban discret qui enlace la nature et guide les voyageurs patients. Dites-moi, sous vos pas et au fil de cette voie dédiée aux marcheurs et aux cyclistes rêveurs, quel est le nombre secret qui baptise ce chemin où le temps semble suspendu ?",
    answerPattern: "^.*109.*$",
    points: 0,
    nextBlock: {
      title: "Lieu validé",
      value: "Vrai/Faux débloqué",
      label: "Restez sur place : place au Vrai/Faux chronométré.",
    },
  },
  {
    id: 6,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Vrai/Faux",
    type: "mcq",
    question: "Le lac est alimenté uniquement par la pluie",
    options: ["Vrai", "Faux"],
    answer: "Faux",
    answerBubble:
      "En réalité, même si la pluie contribue au niveau de l’eau, ce n’est qu’une petite partie.\nLe lac est principalement alimenté par :\n• la rivière de l’Eau d’Heure\n• d’autres apports hydrauliques contrôlés.",
    points: 150,
    timer: 20,
  },
  {
    id: 7,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Vrai/Faux",
    type: "mcq",
    question: "Un ancien village entier repose aujourd’hui sous les eaux du lac.",
    options: ["Vrai", "Faux"],
    answer: "Faux",
    answerBubble:
      "C’est une idée qui revient souvent, mais ici :\n• aucun village complet n’a été englouti\n• il y avait surtout des terres agricoles, des bois et quelques bâtiments isolés.\n\nContrairement à d’autres barrages en Europe, il n’y a pas de « ville fantôme » sous l’eau ici, même si le mythe est tentant.\n\nExemples célèbres ailleurs en Europe :\n• Lac de Resia : un village submergé dans les années 1950, seul le clocher de l’église dépasse encore.\n• Embalse de Sau : un ancien village repose sous le lac, et quand le niveau baisse, les ruines réapparaissent.\n• Lac de Serre-Ponçon : plusieurs villages déplacés ou détruits, avec la chapelle Saint-Michel conservée au milieu des eaux.\n• Ladybower Reservoir : le village de Derwent a été englouti, et lors des sécheresses, des vestiges réapparaissent.",
    points: 150,
    timer: 20,
  },
  {
    id: 8,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Vrai/Faux",
    type: "mcq",
    question: "L’eau du lac peut être déplacée entre différents bassins",
    options: ["Vrai", "Faux"],
    answer: "Vrai",
    answerBubble:
      "Plusieurs lacs sont interconnectés : l’eau peut circuler entre eux selon les besoins grâce à des installations techniques.\nLe barrage de la Plate Taille joue un rôle central dans ce système.\n\nCela permet de gérer :\n• les niveaux d’eau\n• la production d’énergie\n• la sécurité hydraulique.",
    points: 150,
    timer: 20,
  },
  {
    id: 9,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Vrai/Faux",
    type: "mcq",
    question: "Le lac a été créé naturellement au fil du temps",
    options: ["Vrai", "Faux"],
    answer: "Faux",
    answerBubble: "Il s’agit d’un lac artificiel, créé par des barrages dans les années 1970.",
    points: 150,
    timer: 20,
  },
  {
    id: 10,
    stage: "Étape 3 – 50.192726, 4.394856",
    section: "Vrai/Faux",
    type: "mcq",
    question: "Le niveau de l’eau peut varier selon les besoins énergétiques et la gestion du site",
    options: ["Vrai", "Faux"],
    answer: "Vrai",
    answerBubble:
      "Oui : le niveau peut monter ou descendre en fonction de la gestion du réseau.\nLe site est lié à une centrale de pompage-turbinage (production d’électricité).\n\nEn résumé :\n• on stocke de l’eau quand il y a trop d’énergie\n• on la relâche pour produire de l’électricité quand il y a de la demande.",
    points: 150,
    timer: 20,
    nextBlock: {
      title: "Prochaine coordonnée",
      value: "50.201160, 4.387284",
      summaryTemplate: "Avec cette épreuve, vous avez remporté {points} points !",
      label: "Étape 4 – Commencez par le signe distinctif, puis les questions Henryesque.",
    },
  },
  {
    id: 11,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Signe distinctif",
    type: "free",
    question: "Quels points noeuds indique le panneau le plus proche?",
    instructions: "Réponse à relever sur place pour prouver que vous êtes bien au bon endroit.",
    acceptAny: true,
    answerDisplay: "Réponse relevée sur place.",
    points: 0,
    nextBlock: {
      title: "Lieu validé",
      value: "Questions Henryesque débloquées",
      label:
        "Commencez le QCM chronométré : pour marquer, choisissez une mauvaise réponse. Départ à 500 points, -1 point par seconde et -15 points par “mauvaise” réponse.",
    },
  },
  {
    id: 12,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quelle guerre a-t-il vécue ?",
    instructions:
      "Règle Henryesque : pour marquer, choisissez une mauvaise réponse. Capital initial : 500 points, -1 point par seconde et -15 points chaque fois que vous cliquez sur une vraie réponse.",
    options: ["La guerre de Chypre", "La guerre de Corée", "La guerre d’Algérie"],
    answer: "La guerre de Chypre",
    points: 0,
  },
  {
    id: 13,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    type: "mcq",
    question: "Qu’a-t-il reçu à ses 40 ans ?",
    options: [
      "Un vélo et une bouteille d’Ultra",
      "Un vélo et une gourde Ultra",
      "Un VTT et une bouteille d’Ultra",
    ],
    answer: "Un vélo et une bouteille d’Ultra",
    answerDisplay: "Un vélo et une bouteille d’Ultra comme gourde",
    points: 0,
  },
  {
    id: 14,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Dans quelle rue a-t-il grandi ?",
    options: ["Rue planche au pêcheur", "Rue des Tanneurs", "Rue Haute"],
    answer: "Rue planche au pêcheur",
    points: 0,
  },
  {
    id: 15,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quel est son chatbot IA favori ?",
    options: ["Copilot", "ChatGPT", "Claude"],
    answer: "Copilot",
    points: 0,
  },
  {
    id: 16,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Où a t il passé ses dernières vacances ?",
    options: ["Albanie", "Portugal", "Croatie"],
    answer: "Albanie",
    points: 0,
  },
  {
    id: 17,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quel sport pratique-t-il en salle ?",
    options: ["Badminton", "Padel", "Squash"],
    answers: ["Badminton", "Padel"],
    points: 0,
  },
  {
    id: 18,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quel est son totem ?",
    options: ["Eyra", "Mowgli", "Baloo"],
    answer: "Eyra",
    answers: ["Eyra"],
    answerDisplay: "Eyra",
    points: 0,
  },
  {
    id: 19,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    type: "mcq",
    question: "Quelle était sa première voiture ?",
    options: ["Golf", "Golfe", "Gulf"],
    answer: "Golf",
    answerDisplay: "Golf",
    points: 0,
  },
  {
    id: 20,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quelles langues parle t il ?",
    options: ["Français, anglais, espagnol", "Français, néerlandais, allemand", "Français, anglais, portugais"],
    answer: "Français, anglais, espagnol",
    points: 0,
  },
  {
    id: 21,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quel est le pays le plus lointain où il s’est rendu en voiture ?",
    options: ["Iran", "Turquie", "Grèce"],
    answer: "Iran",
    points: 0,
  },
  {
    id: 22,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    type: "mcq",
    question: "Quel était le nom de son école primaire ?",
    options: ["Saint-Jacques", "Saint-Jacque", "Sainte-Jacques"],
    answer: "Saint-Jacques",
    answerDisplay: "Saint-Jacques",
    points: 0,
  },
  {
    id: 23,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "Quel est l'endroit le plus lointain où il ait voyagé ?",
    options: ["La Réunion", "Tokyo", "Le Caire"],
    answers: ["La Réunion", "La Reunion"],
    answerDisplay: "La Réunion",
    points: 0,
  },
  {
    id: 24,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    type: "mcq",
    question: "Dans quelle ville habitait sa grand mère paternelle ?",
    options: ["Courcelles", "Corcelles", "Courcelle"],
    answer: "Courcelles",
    answerDisplay: "Courcelles",
    points: 0,
  },
  {
    id: 25,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    type: "mcq",
    question: "Comment s’appelaient les chèvres ?",
    options: ["Côtelette et Gigot", "Côtelette et Gigaud", "Côtelettes et Gigot"],
    answer: "Côtelette et Gigot",
    answerDisplay: "Côtelette et Gigot",
    points: 0,
  },
  {
    id: 26,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "À quel étage se trouvait sa chambre d’enfance ?",
    options: ["2ème", "2e", "1er"],
    answers: ["2ème", "2e"],
    points: 0,
  },
  {
    id: 27,
    stage: "Étape 4 – 50.201160, 4.387284",
    section: "Questions Henryesque",
    kind: "henry",
    question: "En quelle année a t il déménagé dans sa maison actuelle ?",
    options: ["2002", "2005", "2010"],
    answer: "2002",
    points: 0,
    henryFinal: true,
    nextBlock: {
      title: "Prochaine coordonnée",
      value: "50.202982, 4.376316",
      label: "Étape 5 – Validez le lieu, puis décodez l’énigme.",
    },
  },
  {
    id: 28,
    stage: "Étape 5 – 50.202982, 4.376316",
    section: "Signe distinctif",
    type: "free",
    question:
      "Enracinés précisément au point qui vous a été confié, sans céder à la tentation de vous en éloigner, laissez votre regard explorer les signes qui s’offrent à vous sans faire un pas de plus : quels sont donc les noms des villages qui se révèlent, inscrits sur les panneaux visibles depuis ce lieu exact ?",
    answerPattern: "^(?=.*\\berpion\\b)(?=.*\\bvirelles\\b).*$",
    points: 0,
    nextBlock: {
      title: "Lieu validé",
      value: "Signe distinctif trouvé",
      label: "Vous pouvez maintenant répondre à l’énigme de l’étape 5.",
    },
  },
  {
    id: 29,
    stage: "Étape 5 – 50.202982, 4.376316",
    section: "Énigme",
    type: "free",
    question: "Décodez : JA JPJ / GDMDWWP",
    instructions: "Attention, les espaces comptent. Possibilité d’indice (fait perdre 50 points).",
    answers: [
      "50.205750, 4.363997",
      "50.205750 4.363997",
      "502057504363997",
      "50 205750 4 363997",
    ],
    points: 250,
    hint: {
      text: "Un 3310 vous aurait été bien utile.",
      penalty: -50,
      label: "Voir l’indice (-50 points)",
    },
    answerDisplay: "La bonne piste vous menait aux coordonnées suivantes.",
    nextBlock: {
      title: "Prochaine coordonnée",
      value: "50.205750, 4.363997",
      label: "Étape 6 – Validez le lieu avant les devinettes.",
    },
  },
  {
    id: 30,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Signe distinctif",
    type: "free",
    question:
      "Contemplez l’aval de la vallée sèche d’Erpion, livre ancien aux pages de silence craquelé… Vers quel azimut de la rose des vents s’incline votre être ? Quelle boussole borgne, secrètement fiévreuse, oriente vos pas dans cet immobile suspendu ?",
    answerPattern: "^(?:s\\.?\\s*-?\\s*o\\.?|sud\\s*-?\\s*ouest)$",
    answerDisplay: "Sud Ouest",
    points: 0,
    nextBlock: {
      title: "Lieu validé",
      value: "Devinettes débloquées",
      label: "Restez sur place pour la série de devinettes (20 secondes de chrono, +250 points par bonne réponse et 30 points par bonne liaison).",
    },
  },
  {
    id: 31,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question:
      "Dans quelle région naturelle vallonnée, connue pour ses forêts et ses plateaux, se situent les lacs ?",
    options: [
      "la Fagne et la Famenne (zone de transition)",
      "la Lorraine belge et la Gaume",
      "le Condroz et le Pays de Herve",
      "l’Ardenne et la Hesbaye",
    ],
    answer: "la Fagne et la Famenne (zone de transition)",
    points: 250,
    timer: 20,
  },
  {
    id: 32,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question: "Quelle est l’altitude approximative de la région des lacs (ordre de grandeur) ?",
    options: [
      "entre 200 et 300 mètres au-dessus du niveau de la mer",
      "entre 20 et 30 mètres au-dessus du niveau de la mer",
      "entre 600 et 700 mètres au-dessus du niveau de la mer",
      "entre 1 200 et 1 300 mètres au-dessus du niveau de la mer",
    ],
    answer: "entre 200 et 300 mètres au-dessus du niveau de la mer",
    points: 250,
    timer: 20,
    easterEgg: {
      icon: "🔥",
      text: "ça va ? Votre 4g n'a pas trop chauffée?",
    },
  },
  {
    id: 33,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "free",
    question: "Les eaux des lacs finissent par rejoindre quel grand fleuve européen ?",
    answers: ["la Meuse", "Meuse"],
    answerDisplay: "la Meuse",
    points: 250,
  },
  {
    id: 34,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "match",
    kind: "match-pairs",
    question: "Reliez les communes et leur démographies",
    instructions: "Reliez chaque commune à la bonne démographie.",
    pairs: [
      { left: "Cerfontaine", right: "~4 500" },
      { left: "Froidchapelle", right: "~3 900" },
      { left: "Walcourt", right: "~18 000" },
      { left: "Philippeville", right: "~9 000" },
      { left: "Florennes", right: "~11 000" },
      { left: "Beaumont", right: "~7 000" },
      { left: "Sivry-Rance", right: "~4 800" },
    ],
    pointsPerMatch: 30,
  },
  {
    id: 35,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question: "Peut-on bronzer sur une plage… en regardant des sapins au lieu de palmiers ?",
    options: [
      "oui, sur des plages aménagées au milieu des forêts",
      "non, les plages sont interdites autour des lacs",
      "oui, mais uniquement sur des pontons flottants privés",
      "non, il n’y a que des rochers et aucune plage",
    ],
    answer: "oui, sur des plages aménagées au milieu des forêts",
    points: 250,
  },
  {
    id: 36,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "free",
    question: "Les lacs se trouvent à cheval sur deux provinces. Lesquelles ?",
    answerPattern: "^(?=.*\\bnamur\\b)(?=.*\\bhainaut\\b).*$",
    answerDisplay: "Province de Namur et Province de Hainaut",
    points: 250,
    timer: 20,
  },
  {
    id: 37,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question:
      "Quelle espèce dont on en fait l’élevage, dépasse la population de la ville de Cerfontaine sur le même territoire ?",
    options: ["Les poissons", "Les moutons", "Les chèvres", "Les chevaux"],
    answer: "Les poissons",
    points: 250,
    timer: 20,
  },
  {
    id: 38,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question:
      "Quel secteur économique historique de la région a le + bénéficié de la gestion de l’eau du barrage de l’eau d’heure ?",
    options: [
      "l’industrie (sidérurgie, notamment dans le bassin de Charleroi)",
      "l’horlogerie artisanale",
      "la culture de la vigne",
      "la construction navale",
    ],
    answer: "l’industrie (sidérurgie, notamment dans le bassin de Charleroi)",
    points: 250,
    timer: 20,
  },
  {
    id: 39,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "free",
    question: "Quel grand parc naturel couvre une partie de cette région autour des lacs ?",
    answerPattern: "^(?=.*\\bviroin\\b)(?=.*\\bhermeton\\b).*$",
    answerDisplay: "le Parc naturel Viroin-Hermeton",
    points: 250,
  },
  {
    id: 40,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "slider",
    kind: "range-slider",
    question: "Quelle est la superficie totale approximative des lacs ?",
    instructions: "Utilisez la barre de grandeur de 0 à 1500 hectares.",
    slider: { min: 0, max: 1500, step: 1, unit: "ha" },
    target: 600,
    tolerance: 60,
    points: 250,
    answerDisplay: "environ 600 hectares (soit 6 km²)",
  },
  {
    id: 41,
    stage: "Étape 6 – 50.205750, 4.363997",
    section: "Devinettes",
    type: "mcq",
    question: "Peut-on dormir sur l’eau… sans bateau ni natation et sans s’appeler Jésus ?",
    options: [
      "oui, avec des hébergements flottants ou au bord direct des lacs",
      "non, dormir sur l’eau y est interdit",
      "oui, mais seulement dans un voilier",
      "non, il n’existe que des campings à plus de 10 km",
    ],
    answer: "oui, avec des hébergements flottants ou au bord direct des lacs",
    points: 250,
    nextBlock: {
      title: "Prochaine coordonnée",
      value: "50.188382, 4.346416",
      label:
        "Étape 7 – Vous devrez aussi passer par le point 50.203559, 4.361448 avant la suite.",
    },
  },
  {
    id: 42,
    stage: "Étape 7 – 50.188382, 4.346416",
    section: "Accès défi feuilles",
    kind: "numeric-bonus",
    type: "free",
    question: "Combien de mètres de berges voyez-vous ?",
    instructions:
      "Entrez une estimation entre 0 et 18500. Bonus caché : votre valeur divisée par 100 sera ajoutée aux points.",
    answerPattern: "^-?\\d+$",
    answerDisplay: "Bonus berges enregistré.",
    points: 0,
    unitPoints: 0.01,
    minValue: 0,
    maxValue: 18500,
    rejectOutOfRange: true,
    absurdWrongMessage:
      "Même avec des yeux bioniques, impossible d’avoir ce nombre de berges 😄 Restez entre 0 et 18500.",
    outOfRangeMessage: "Valeur invalide : entrez un nombre entre 0 et 18500 pour continuer.",
    nextBlock: {
      title: "Défi feuilles débloqué",
      value: "Épreuve feuilles",
      label: "Passez maintenant à l’épreuve des feuilles.",
    },
  },
  {
    id: 43,
    stage: "Étape 7 – 50.188382, 4.346416",
    section: "Épreuve feuilles",
    kind: "acknowledgement",
    question: "Rapportez un maximum de feuilles d’arbres différentes : elles seront comptées à l’arrivée.",
    instructions:
      "Règles : 1) Toutes les feuilles doivent être différentes. 2) Comptage à l’arrivée. 3) Chaque feuille différente = 50 points. Appuyez sur OK pour afficher la prochaine coordonnée.",
    answerDisplay: "Épreuve feuilles enregistrée.",
    points: 0,
    nextBlock: {
      title: "Prochaine coordonnée",
      value: "50.186963, 4.374291",
      label: "Étape 8 – Dernière zone du parcours.",
    },
  },
  {
    id: 44,
    stage: "Étape 8 – 50.186963, 4.374291",
    section: "Objet caché",
    kind: "acknowledgement",
    question: "Retrouvez l’objet caché dans les environs : sa présence sera vérifiée en réel à l’arrivée.",
    instructions: "Appuyez sur OK pour passer au dernier choix.",
    answerDisplay: "Objet caché à vérifier à l’arrivée.",
    nextBlock: {
      title: "Dernier choix",
      value: "Valeur des points",
      label: "Si l’objet a été retrouvé, choisissez si la valeur finale des points sera positive ou négative (500 points).",
    },
  },
  {
    id: 45,
    stage: "Étape 8 – 50.186963, 4.374291",
    section: "Bonus / malus final",
    type: "mcq",
    kind: "choice-award",
    question: "Celui qui l’a retrouvé choisit : la valeur des points sera…",
    options: ["Positive (+500)", "Négative (-500)"],
    choicePoints: {
      "Positive (+500)": 500,
      "Négative (-500)": -500,
    },
    answerDisplay: "Choix final enregistré.",
    points: 0,
  },
];
