/**
 * Questions de la balade – Activité du 13/06
 *
 * Champs complémentaires possibles :
 *   answers      : plusieurs réponses acceptées (string[])
 *   answerPattern: regex (string) pour valider une réponse libre
 *   acceptAny    : toute réponse non vide est acceptée
 *   answerDisplay: texte affiché comme "bonne réponse"
 */
const QUESTIONS = [
  {
    id: 1,
    type: "free",
    question:
      "Défi de départ (Mölkky coopératif) : quel score exact devez-vous atteindre ensemble ?",
    image: null,
    options: null,
    answer: "50",
    timer: 30,
    points: 1000,
    coordinates: "50.191682, 4.383208",
    coordinatesLabel: "Étape 2 – Rejoignez le premier point du jeu de piste.",
  },
  {
    id: 2,
    type: "free",
    question:
      "Quel mot imaginaire est formé par les premières lettres des panneaux directionnels visibles ?",
    image: null,
    options: null,
    answer: "CVCDBC",
    timer: 40,
    points: 150,
    coordinates: "50.192726, 4.394856",
    coordinatesLabel: "Étape 3 – Continuez vers le point suivant.",
  },
  {
    id: 3,
    type: "free",
    question:
      "Sur la voie dédiée aux marcheurs et cyclistes, quel est le numéro du chemin ?",
    image: null,
    options: null,
    answer: "109",
    timer: 30,
    points: 250,
    coordinates: "50.192726, 4.394856",
    coordinatesLabel: "Restez sur zone : place au défi Vrai/Faux chronométré.",
  },
  {
    id: 4,
    type: "mcq",
    question: "Le lac est alimenté uniquement par la pluie.",
    image: null,
    options: ["Vrai", "Faux", "Impossible à savoir", "Seulement en hiver"],
    answer: "Faux",
    timer: 15,
    points: 250,
    coordinates: "50.192726, 4.394856",
    coordinatesLabel: "Continuez le Vrai/Faux sur place.",
  },
  {
    id: 5,
    type: "mcq",
    question: "Un village entier repose aujourd'hui sous les eaux du lac.",
    image: null,
    options: ["Vrai", "Faux", "Seulement l’église", "Seulement le cimetière"],
    answer: "Faux",
    timer: 15,
    points: 250,
    coordinates: "50.192726, 4.394856",
    coordinatesLabel: "Continuez le Vrai/Faux sur place.",
  },
  {
    id: 6,
    type: "mcq",
    question: "L’eau du lac peut être déplacée entre différents bassins.",
    image: null,
    options: ["Vrai", "Faux", "Jamais", "Seulement en été"],
    answer: "Vrai",
    timer: 15,
    points: 250,
    coordinates: "50.192726, 4.394856",
    coordinatesLabel: "Continuez le Vrai/Faux sur place.",
  },
  {
    id: 7,
    type: "mcq",
    question: "Le lac a été créé naturellement au fil du temps.",
    image: null,
    options: ["Vrai", "Faux", "Partiellement", "Seulement avant 1970"],
    answer: "Faux",
    timer: 15,
    points: 250,
    coordinates: "50.192726, 4.394856",
    coordinatesLabel: "Dernière question Vrai/Faux.",
  },
  {
    id: 8,
    type: "mcq",
    question:
      "Le niveau de l’eau peut varier selon les besoins énergétiques et la gestion du site.",
    image: null,
    options: ["Vrai", "Faux", "Uniquement la nuit", "Uniquement après la pluie"],
    answer: "Vrai",
    timer: 15,
    points: 250,
    coordinates: "50.201160, 4.387284",
    coordinatesLabel: "Étape 4 – Rejoignez le point suivant pour les questions de papa.",
  },
  {
    id: 9,
    type: "mcq",
    question: "Question papa : quel est son chatbot IA favori ?",
    image: null,
    options: ["ChatGPT", "Claude", "Copilot", "Gemini"],
    answer: "Copilot",
    timer: 20,
    points: 200,
    coordinates: "50.201160, 4.387284",
    coordinatesLabel: "Restez sur l’étape 4 pour la suite des questions papa.",
  },
  {
    id: 10,
    type: "mcq",
    question: "Question papa : où a-t-il passé ses dernières vacances ?",
    image: null,
    options: ["Portugal", "Albanie", "Croatie", "Grèce"],
    answer: "Albanie",
    timer: 20,
    points: 200,
    coordinates: "50.201160, 4.387284",
    coordinatesLabel: "Encore une question papa.",
  },
  {
    id: 11,
    type: "mcq",
    question: "Question papa : quelles langues parle-t-il ?",
    image: null,
    options: [
      "Français, anglais, espagnol",
      "Français, néerlandais, allemand",
      "Anglais, italien, espagnol",
      "Français, anglais, portugais",
    ],
    answer: "Français, anglais, espagnol",
    timer: 20,
    points: 200,
    coordinates: "50.201160, 4.387284",
    coordinatesLabel: "Dernière question papa.",
  },
  {
    id: 12,
    type: "mcq",
    question: "Question papa : quelle guerre a-t-il vécue ?",
    image: null,
    options: ["Guerre de Corée", "Guerre de Chypre", "Guerre du Golfe", "Guerre d’Algérie"],
    answer: "Guerre de Chypre",
    timer: 20,
    points: 200,
    coordinates: "50.202982, 4.376316",
    coordinatesLabel: "Étape 5 – Direction le point suivant.",
  },
  {
    id: 13,
    type: "mcq",
    question:
      "Depuis le point exact, quels villages sont visibles sur les panneaux ?",
    image: null,
    options: [
      "Erpion et Virelles",
      "Walcourt et Cerfontaine",
      "Froidchapelle et Florennes",
      "Philippeville et Beaumont",
    ],
    answer: "Erpion et Virelles",
    timer: 25,
    points: 300,
    coordinates: "50.205750, 4.363997",
    coordinatesLabel: "Étape 6 – Rejoignez l’aval de la vallée sèche d’Erpion.",
  },
  {
    id: 14,
    type: "mcq",
    question:
      "Vers quel azimut de la rose des vents vous orientez-vous à l’aval de la vallée sèche d’Erpion ?",
    image: null,
    options: ["Nord-Est", "Sud-Ouest", "Sud-Est", "Nord-Ouest"],
    answer: "Sud-Ouest",
    timer: 20,
    points: 300,
    coordinates: "50.203559, 4.361448",
    coordinatesLabel: "Point de passage imposé avant la suite.",
  },
  {
    id: 15,
    type: "free",
    question:
      "Les eaux des lacs finissent par rejoindre quel grand fleuve européen ?",
    image: null,
    options: null,
    answer: "Meuse",
    timer: 25,
    points: 250,
    coordinates: "50.188382, 4.346416",
    coordinatesLabel: "Étape 7 – Direction les berges.",
  },
  {
    id: 16,
    type: "mcq",
    question:
      "Les lacs se trouvent à cheval sur deux provinces. Lesquelles ?",
    image: null,
    options: [
      "Namur et Hainaut",
      "Namur et Liège",
      "Hainaut et Brabant wallon",
      "Liège et Luxembourg",
    ],
    answer: "Namur et Hainaut",
    timer: 25,
    points: 250,
    coordinates: "50.188382, 4.346416",
    coordinatesLabel: "Dernier défi de l’étape 7.",
  },
  {
    id: 17,
    type: "free",
    question:
      "Combien de mètres de berges voyez-vous ? (Tout nombre est accepté)",
    image: null,
    options: null,
    answerPattern: "^\\d+$",
    answerDisplay: "Toute valeur numérique était acceptée.",
    timer: 20,
    points: 250,
    coordinates: "50.186963, 4.374291",
    coordinatesLabel: "Étape 8 – Rejoignez la zone de l’objet caché.",
  },
  {
    id: 18,
    type: "free",
    question:
      "Objet caché : indiquez ce que vous avez trouvé pour valider la fin du parcours.",
    image: null,
    options: null,
    acceptAny: true,
    answerDisplay: "Validation libre : toute réponse non vide était acceptée.",
    timer: 45,
    points: 500,
    coordinates: "50.186963, 4.374291",
    coordinatesLabel: "Parcours terminé – retour vers la zone barbecue (point 8).",
  },
];
